// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Prisma's advisory
    // lock for `migrate deploy` doesn't work reliably through Neon's
    // PgBouncer pooler (DATABASE_URL). The app's own runtime client
    // (src/lib/prisma.ts) still uses the pooled DATABASE_URL directly.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
